services:
  backend:
    build: ./backend
    container_name: know_your_fan_backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - know-your-fan-network

networks:
  know-your-fan-network:
